susan: susan.c Makefile
	$(CC) -static -O4 -o susan susan.c -lm 

clean:
	rm -rf susan output*
CROSS_COMPILE = /opt/alphaev67-unknown-linux-gnu/bin/alphaev67-unknown-linux-gnu
CC=$(CROSS_COMPILE)-gcc
